-- MySQL Script generated by MySQL Workbench
-- Wed Oct 27 21:16:23 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema tccadocao
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tccadocao
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tccadocao` DEFAULT CHARACTER SET utf8 ;
USE `tccadocao` ;

-- -----------------------------------------------------
-- Table `tccadocao`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tccadocao`.`usuario` (
  `id_usuario` INT(11) NOT NULL AUTO_INCREMENT,
  `nomeusuario` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `deleted` TINYINT(1) NULL DEFAULT 0,
  `endereco` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tccadocao`.`adocao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tccadocao`.`adocao` (
  `id_adocao` INT(11) NOT NULL AUTO_INCREMENT,
  `data` DATETIME NOT NULL,
  `statusAdocao` VARCHAR(45) NOT NULL,
  `deleted` TINYINT(1) NULL DEFAULT NULL,
  `fk_id_usuario` INT(11) NOT NULL,
  PRIMARY KEY (`id_adocao`),
  INDEX `fk_id_usuario` (`fk_id_usuario` ASC) VISIBLE,
  CONSTRAINT `adocao_ibfk_1`
    FOREIGN KEY (`fk_id_usuario`)
    REFERENCES `tccadocao`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tccadocao`.`animais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tccadocao`.`animais` (
  `id_animais` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `local` VARCHAR(300) NOT NULL,
  `deleted` TINYINT(1) NULL DEFAULT 0,
  `fk_id_adocao` INT(11) NULL DEFAULT NULL,
  `imagem` MEDIUMBLOB NULL DEFAULT NULL,
  `imagemextensao` VARCHAR(45) NULL DEFAULT NULL,
  `descricao` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`id_animais`),
  INDEX `animais_ibfk_1` (`fk_id_adocao` ASC) VISIBLE,
  CONSTRAINT `animais_ibfk_1`
    FOREIGN KEY (`fk_id_adocao`)
    REFERENCES `tccadocao`.`adocao` (`id_adocao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
